'use strict';
const fullName = 'Daniel Yount';
const isCool = false;
const totalPets = 1;
console.log(`The variable fullName has the value: ${fullName}.`);
console.log(`The variable isCool has the value: ${isCool}.`);
console.log(`The variable totalPets has the value ${totalPets}.`);
console.log(`The variable fullName has the type: ${typeof fullName}.`);
console.log(`The variable isCool has the type: ${typeof isCool}.`);
console.log(`The variable totalPets has the type ${typeof totalPets}.`);
const empty = null;
console.log(`The variable empty has the value of: ${empty}.`);
console.log(`The variable empty has the type of: ${typeof empty}.`);
const nothing = undefined;
console.log(`The variable nothing has the value of: ${nothing}.`);
console.log(`The variable nothing has the type of: ${typeof nothing}.`);
